# Generated by Django 4.0.3 on 2022-04-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_contactuser_alter_category_image_alter_post_mage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
