# Generated by Django 4.0.3 on 2022-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_comments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(max_length=254)),
                ('description', models.TextField(default='Admin E-Mail Address')),
            ],
            options={
                'verbose_name_plural': ' Admin Email Controller Panel',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_date'], 'verbose_name_plural': 'Comments'},
        ),
    ]
